### PR TITLE
optimise adam solver

### PR DESCRIPTION
**Pull request by kashif**
moved two calculations outside the for-zip loop

### CODE REVIEW

**Comment by f0k** [comment]
Looks fine. Not sure if it's easier to read than before, but maybe it helps to make clear `t` and `a_t` are the same for every parameter.

Note that this doesn't actually optimize anything -- creating the expression graph may be a few microseconds faster, but runtime performance is exactly the same (the loop is only executed once to create the update dictionary which is then compiled into a function, it is not executed at each update step).

Any other opinions?

**Comment by kashif** [comment]
true... just a bit clearer then

**Comment by f0k** [comment]
Merging since there are no more comments, thank you!

**Comment by kashif** [comment]
bitte!

**Pull request merged**
