### PR TITLE
Coverage for pool.py, helper.py

### PR DESCRIPTION
**Pull request by ebenolson**
Adds a few tests to complete coverage for pool.py, and adds `pragma no cover` for the deprecated helper functions.

### CODE REVIEW

**Comment by ebenolson** [comment]
`helper.py` has full coverage except for https://github.com/ebenolson/Lasagne/blob/more_tests/lasagne/layers/helper.py#L302

I couldn't figure out how to trigger this, and it looks like it was copy-pasted from get_output. Is it a necessary check?

**Comment by f0k** [comment]
> Is it a necessary check?

Good catch! The `try..except` clause around that is unneeded, it's impossible for a layer not to have a defined input shape. It seems getting the test coverage to 100% may uncover things that would go unnoticed at 90% :)

**Comment by benanne** [comment]
We're already well into the 90% range thanks to @ebenolson's work, so we might as well go all the way!  Thanks a lot for this, I'll have a closer look tomorrow :)

**Comment by benanne** [comment]
No further comments from me, I'm good with merging. Feel free to remove that `try..except` as well :)

**Comment by ebenolson** [comment]
Great, made that change.

**Comment by benanne** [comment]
Merging

**Pull request merged**
