### PR TITLE
docs/user/about: Added comparision with Caffe

### PR DESCRIPTION
**Pull request by MartinThoma**
I've added a comparison about Caffe / Lasagne to the documentation as well as a little bit more about the "history" of Lasagne (who develops it and when did development start).
I think this information is interesting, because people can take a look at your websites and see what you're working on and get some confidence that Lasagne might be worth a try (I hope I didn't forget any core contributor).

The comparison of Caffe / Lasagne can certainly be better, but I think it's a good start. Other frameworks for which I we could eventually add comparisons are

* Torch: http://torch.ch/
* DL4J: http://deeplearning4j.org/

### CODE REVIEW

**Comment by f0k** [comment]
Sorry, except for the first sentence I'd have written everything differently and/or not included it in the user documentation at all. I'd list the contributors as part of the release notes, but everyone, not just the core team (Theano did that quite well for 0.6), and I wouldn't put a superficial comparison to Caffe as one of the first things a new user will see! In general, while I appreciate your input, I think we should focus on documenting the code before starting any meta-documentation -- please pick your favorite at #203 if you're in the mood for writing :) A nice "about" text or FAQ can wait until after the first release.

**Comment by benanne** [comment]
I think there is room for something like this in the docs, but maybe not on the front page right now. It's a bit unfortunate that this would be the first thing the user sees. We don't really want to market ourselves as an alternative to Caffe, nor is Lasagne a 'reaction to it', so it seems out of place to put this much emphasis on such a comparison. 

But of course that's just down to adding more content to the front page first (a more neutral description of Lasagne and maybe a brief 'Getting started' section would be good for that). Eventually I think having a comparison to some other libraries in this space in our docs, highlighting which use cases each library is better suited for, would definitely be valuable.

**Comment by f0k** [comment]
> a more neutral description of Lasagne and maybe a brief 'Getting started' section would be good for that

I like the structure of the [cudamat front page](https://github.com/cudamat/cudamat) (but I might be biased). I know we're talking about the front page for the documentation here, but that could be largely the same: A description of what it's about, a short code example illustrating the key aspect, and links to further information (installation, user guide, API reference).

> Eventually I think having a comparison to some other libraries in this space in our docs, highlighting which use cases each library is better suited for, would definitely be valuable.

I'd collect such meta-documentation in a FAQ at the *end* of the docs or in the wiki, along with an explanation of the name (that will be fun to write) and these sorts of things. "How is Lasagne different from pylearn2?", "How is Lasagne different from caffe?", ... But again, this can wait.

**Comment by benanne** [comment]
> I like the structure of the cudamat front page (but I might be biased). 

It looks great, and gives you a rough idea of what the library is about at a glance. We should aim for the same effect.

> I'd collect such meta-documentation in a FAQ at the end of the docs or in the wiki, along with an explanation of the name (that will be fun to write) and these sorts of things. "How is Lasagne different from pylearn2?", "How is Lasagne different from caffe?", ... But again, this can wait.

Agreed, sounds good.

**Comment by MartinThoma** [comment]
> I think we should focus on documenting the code before starting any meta-documentation -- please pick your favorite at #203 if you're in the mood for writing :)

I have pull request going for one of those, but there was an issue with possible rebasing due to #182. I'll rather wait until this is done before I start writing documentation. I am currently preparing a much simpler example using XOR. I could probably calculate the values for those by hand so that we can add more (meaningful) tests for very simple networks.

Ok. So I close this pull request and try the FAQ approach when I have time again / when the other stuff is done.

**Pull request closed without merging**
