### PR TITLE
move srng into noise layers, seed from numpy

### PR DESCRIPTION
**Pull request by ebenolson**
This partially addresses https://github.com/Lasagne/Lasagne/issues/6, which came up on the mailing list again a few days ago (https://groups.google.com/forum/#!topic/lasagne-users/85-6gxygtIo).

By making `_srng` a member of each layer which is initialized from numpy, the user only needs to call `np.random.seed` at the start of their code to get reproducible behavior.

### CODE REVIEW

**Comment by f0k** [comment]
+1. This also circumvents the memory leak Colin found when instantiating a lot of dropout layers and discarding them (https://github.com/Theano/Theano/issues/2335#issuecomment-66855136).

**Comment by f0k** [comment]
Thinking about it, do we really want the base class for just one line in the constructor? If we have a base class, we probably need to put it in `__all__` as well and give it a proper docstring that explains what it's for and that you shouldn't instantiate it. Right now it wouldn't even be included in Sphinx, but you would see that the two noise layers are derived from an undocumented `NoiseLayer` class. Maybe it's clearer for now to just instantiate `self._rng` in the two noise layer constructors directly.

**Comment by ebenolson** [comment]
That's true, I was initially contemplating adding a method to set the seed, and it could simplify a potential future move away from the numpy internal rng. But with only two noise layers so far it's not really needed.

I also hoped it would help avoid situations where someone creates new stochastic layers that aren't seeded the same way.

**Comment by f0k** [comment]
> That's true, I was initially contemplating adding a method to set the seed, and it could simplify a potential future move away from the numpy internal rng.

Okay, it would help stochastic layers outside of the Lasagne repository to seamlessly support different seeding methods if we ever extend the `NoiseLayer` base class in this respect. If we want that, we should document that the purpose of the `NoiseLayer` is more than saving a single line of code in the constructor. Right now I fear it mostly serves to obfuscate the code.

> I also hoped it would help avoid situations where someone creates new stochastic layers that aren't seeded the same way.

I think when somebody creates a new stochastic layer, that somebody will probably copy & paste the dropout layer or gaussian noise layer as a starting point because it explains the `deterministic` keyword argument. Without a `NoiseLayer` base class, this code is fully self-contained, and it's clear how to change the RNG if that's useful.

> But with only two noise layers so far it's not really needed.

Right. I think I'd prefer to drop it, because it makes the code slightly more difficult to understand. We can still add it back if we extend the API to allow users to specify a custom seeding RNG. But in general, I very much appreciate the foresight! A good `NoiseLayer` docstring would convince me as well, if you prefer to keep it!

**Comment by ebenolson** [comment]
Let's go with simple for now.

 I think it would also be good to add a section to the docs somewhere on reproducibility, I guess `tutorial.rst` would be the place? Or could start a FAQ section.

**Comment by f0k** [comment]
Looks good, thanks! I'll leave this up for Sander to merge in case he's got any comment.

> I think it would also be good to add a section to the docs somewhere on reproducibility, I guess tutorial.rst would be the place? Or could start a FAQ section.

Probably both places -- part of the Tutorial / the included MNIST example (that we don't have yet), and part of the FAQ (that we don't have yet). We'll keep that in mind.

**Comment by benanne** [comment]
lgtm, merging

**Pull request merged**
