### PR TITLE
Issue #625 Make FlattenLayer support `None` in input shape

### LINKED ISSUE #625: Make FlattenLayer support `None` in input shape
Currently, `FlattenLayer` does not work if any of the axes that are flattened have a shape of `None`. So this does not work:

```
l = lasagne.layers.InputLayer((None, None, None))
l = lasagne.layers.FlattenLayer(l)
```

Instead, users get an unhelpful error message because Lasagne attempts to compute the output shape nevertheless: 

```
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

(see https://groups.google.com/forum/#!topic/lasagne-users/0fa-GRH8wwo )

The shape computation is here: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/shape.py#L46-L49

I think we can easily adapt this to simply return `None` for the flattened dimension of any of the constituent dimensions from the input shape have size `None`.

Any takers? :) If nobody wants to I can probably do a PR this weekend. Shouldn't be too much work, but I don't have much time to spare at the moment.

### PR DESCRIPTION
**Pull request by chuzui**
Fixes #625

### CODE REVIEW

**Comment by f0k** [comment]
That's wrong, unfortunately, `get_output_shape_for()` must not return `None`. We don't have a set of generic `Layer` tests that all layers have to go through, maybe we should? It's difficult to accomplish, though.

The old implementation:
```python
shp = [input_shape[i] for i in range(self.outdim-1)]
shp += [int(np.prod(input_shape[(self.outdim-1):]))]
return tuple(shp)
```
should change to
```python
to_flatten = input_shape[self.outdim:]
if any(s is None for s in to_flatten):
    flattened = None
else:
    flattened = int(np.prod(to_flatten))
return input_shape[:self.outdim-1] + (flattened,)
```

**Comment by chuzui** [comment]
Tnank you, f0k. I misunderstood this function.

**Comment by f0k** [comment]
Perfect, thanks! Will merge tomorrow if there are no further comments.

**Comment by benanne** [comment]
LGTM, thanks for contributing!

**Pull request merged**
