### PR TITLE
SpatialDropoutLayer

### PR DESCRIPTION
**Pull request by gzuidhof**
Hi there,

I think a spatial dropout layer (which is also called feature dropout) would make a nice addition to Lasagne. It was already discussed half a year ago [here](https://groups.google.com/forum/#!topic/lasagne-users/qOV7i4SFUH8). 

This implementation is an adaptation of the standard dropout layer found in lasagne.

### CODE REVIEW

**Comment by f0k** [comment]
Thank you! I'd rather extend the `DropoutLayer` with a `shared_axes` argument (defaulting to the empty tuple) so you can also use it to dropout rows or columns (or any combination of that). Would you be willing to do this instead? Otherwise I'll do it myself when I've got time.

**Comment by gzuidhof** [comment]
Sure, I can contribute that :+1:.

**Comment by benanne** [comment]
Thanks for the PR! I'm fine with either. Maybe extending the current `DropoutLayer` is a bit more natural, at the expense of making the code for that slightly less readable.

**Comment by gzuidhof** [comment]
I was thinking about how to implement this. It is very straightforward if the first few dimensions are "dropped out altogether". But is there a use case for dropping out say the second and the third dimension (given `<image, feature_channel, x, y>`)?

Making this `shared_axes` an integer which denotes from which (shape-)index  everything should either be dropt or kept would keep the implementation a lot simpler.

**Comment by f0k** [comment]
> But is there a use case for dropping out say the second and the third dimension?

I can think of use cases for many different `shared_axes` values:
* shared_axes=(): standard dropout
* shared_axes=(0): batch-wise dropout (use the same dropout mask across axis 0)
* shared_axes=(2,3): drop full feature maps (use the same dropout mask across axes 2 and 3)
* shared_axes=(1,2): drop full frequency bands of spectrograms (use the same dropout mask across axes 1 and 2)

We wouldn't want a separate dropout layer class for each variant. We could have a `spatial_dropout()` shortcut, though.

> Making this `shared_axes` an integer which denotes from which (shape-)index everything should either be dropt or kept would keep the implementation a lot simpler.

I can do the implementation myself if you're not under time pressure! This has been on my TODO list for a while.

**Pull request closed without merging**
