### PR TITLE
Add Docker images to docs

### PR DESCRIPTION
**Pull request by Kaixhin**
I've added information on the Docker images to the docs, which closes https://github.com/Lasagne/Lasagne/issues/411.

I have also successfully run the test suite on both CPU and CUDA containers without errors.

### CODE REVIEW

**Comment by f0k** [comment]
Thanks, this looks really great! The text is good, the markup looks correct, and the links all work. I'll wait to see if coveralls will finish at some point, but other than that I'm fine with merging!

**Comment by Kaixhin** [comment]
Awesome! If there are any problems with the images just raise an issue in my [repo](https://github.com/Kaixhin/dockerfiles), or mention me if someone raises an issue in this repo.

**Comment by f0k** [comment]
Closing/Reopening to re-trigger travis and coveralls. (It looks bad to merge a commit that doesn't have a green checkmark...)

**Comment by benanne** [comment]
Something's wrong with coveralls I guess? It shouldn't take this long.

**Comment by f0k** [comment]
Difficult to say. status.coveralls.io doesn't tell anything. I'll just merge it, and if other PRs run into the same problem, we should probably ask coveralls.

**Pull request merged**
