### PR TITLE
Add kwarg to recurrent layers to return only final output

### LINKED ISSUE #471: Recurrent layers: "Keep final time step" possibly suboptimal
Recurrent layers are frequently used in a way that only their final output for a time sequence needs to be propagated. There's an optimization for Theano's scan function that recognizes the case:
```python
outputs, updates = theano.scan(...)
keep = outputs[-1]
```
In Lasagne, this use case is currently supported by adding a SliceLayer on top of a RecurrentLayer:
```python
layer = RecurrentLayer(...)
layer = SliceLayer(layer, -1, axis=1)
```
However, the recurrent layers shuffle the scan output from (timesteps, batchsize, features) to (batchsize, timesteps, features), so Theano will never encounter a subtensor(scan(...)) sequence, but a subtensor(dimshuffle(scan(...))) sequence. We need to check if that case is optimized as well.

Lasagne's recurrent layers also accept an `unroll_scan` keyword argument, which unrolls the scan into a graph that ends in a `T.stack()` for stacking all the time steps. Again, if there's a SliceLayer on top to only keep the last output, Theano will see a subtensor(dimshuffle(stack(...))) sequence. We need to check if that case is optimized into keeping the last time step only, or whether it will actually stack all the time steps first.

Both is complicated by the fact that for layers processing the sequences in reverse order, there will also be a subtensor(::-1) between the recurrent layer's output and the SliceLayer. We also need to check whether those cases are optimized.

For the first case, Theano would need an optimization subtensor(dimshuffle(...)) -> dimshuffle(subtensor(...)), but maybe it has this. For the second case, it would need an optimization subtensor(dimshuffle(stack(...))) -> ..., but maybe it has this already. For reverse layers, Theano would need to be able to turn x[::-1][0] into x[-1] before applying the other optimizations.

Alternatively, Lasagne's recurrent layers could get a `final_state_only` keyword argument that tells them to keep the final state only and constructs the appropriate graph. That would solve all problems at once, but only for Lasagne.

### PR DESCRIPTION
**Pull request by craffel**
Resolves #471.  I opted for `return_final`; it has the same meaning as `only_return_final` but is shorter to type.

### CODE REVIEW

**Comment by craffel** [comment]
Writing this PR reminded me of how much code duplication we have and how badly we need #425

**Comment by f0k** [comment]
I suggested `only_return_final` because to me `return_final=False` suggests it would omit the final state, and `return_final=True` suggests it would include it (as it does now). If three words are too long, what about `only_final` or `final_only`?

**Comment by craffel** [comment]
Ok, changed to `only_return_final`.

**Comment by f0k** [comment]
Looks good, but could you please update the example in the same commit? It shouldn't use the `SliceLayer(..., -1)` any longer. Cheers!

**Comment by craffel** [comment]
> Looks good, but could you please update the example in the same commit? It shouldn't use the SliceLayer(..., -1) any longer. Cheers!

Ok, done.

**Comment by f0k** [comment]
Coveralls found a line not covered: https://coveralls.io/builds/4167558/source?filename=lasagne%2Flayers%2Frecurrent.py#L910

**Comment by f0k** [comment]
Looks good to merge now! If there are no further comments, I'll merge it tomorrow.
PS: Sorry for the slow/incremental review.

**Comment by craffel** [comment]
> PS: Sorry for the slow/incremental review.

No worries, thanks as always for your thoroughness.

**Comment by f0k** [comment]
Merged, thanks again!

**Pull request merged**
