### PR TITLE
Add TransposeConv2DLayer

### PR DESCRIPTION
**Pull request by fvisin**
Add a `TransposeConv2DLayer` to perform upsampling.
This layer applies a transposed convolution by means of using the gradient of the corresponding "normal" convolution *in the forward pass*.

### CODE REVIEW

**Comment by f0k** [comment]
Thanks, it's a duplicate of #610 though. How did you manage to bypass the coverage test? :)

**Comment by fvisin** [comment]
Oh, I didn't notice the new commits on #610! 
I have been using this Layer for a while on the `conv2d_grad_wrt_inputs` development branch of Theano, waiting for it to be merged to finalize this PR.

Sorry about the duplication, let me know if you want me to modify this PR or close it. 
In the second case, I suggest you don't use the `AbstractConv2d_gradInputs` directly but rather use `conv2d_grad_wrt_inputs` for two reasons: 1) it verifies that all the arguments are of the expected type and 2) it will do some of the work for you when you don't specify all the elements of the `input_shape`.

**Comment by fvisin** [comment]
...I almost forgot, to bypass the coverage test I used some arcane Theano magic! :P
Jokes apart, I can add some tests if you decide to keep this PR.

**Comment by f0k** [comment]
> Oh, I didn't notice the new commits on #610!

Sorry for being so slow with it, I'm constantly held back by more important work...

> Sorry about the duplication, let me know if you want me to modify this PR or close it.

Mhm, I think I'd prefer continuing on the other PR since its documentation is more complete (note that I also found your report, nice to have something complete to link to!).
Also your code has a few things that'd need fixing (calling `get_output` in the constructor, `gpu_contiguous` in `convolve`, and I'm not sure about the `input_shape` parameter). However, I'd appreciate feedback on which interface to choose in https://github.com/Lasagne/Lasagne/pull/610#issuecomment-205008953!

> I suggest you don't use the `AbstractConv2d_gradInputs` directly but rather use `conv2d_grad_wrt_inputs`

All right, will do!

**Comment by fvisin** [comment]
> Sorry for being so slow with it, I'm constantly held back by more important work...

No worries, I can say the same for my PR :)

> Mhm, I think I'd prefer continuing on the other PR since its documentation is more complete 

Yes, I agree.

>(note that I also found your report, nice to have something complete to link to!).

I noticed, thank you! 

> Also your code has a few things that'd need fixing (calling get_output in the constructor, gpu_contiguous in convolve, and I'm not sure about the input_shape parameter). 

I call `get_output` to be able to work with variable sized input (i.e. to get a symbolic shape). Is there a better way to do it? I use it a lot in my code (private repo), but I never liked it.
edit: I just noticed your comment saying that your code handles variable sized input. I will check how you do it. :)

> However, I'd appreciate feedback on which interface to choose in #610 (comment)!

Sure!

**Pull request closed without merging**
