### PR TITLE
rename MultipleInputsLayer to MergeLayer

### PR DESCRIPTION
**Pull request by benanne**
This addresses #200. I grepped for `MultipleInputsLayer` and changed all instances, so hopefully I didn't miss any.

py.test is still broken on this machine so I wasn't able to run the tests. Counting on Travis! I'll try to sort that out tonight.

### CODE REVIEW

**Comment by f0k** [comment]
Uh, please don't merge this before #182. It will be a pain to rebase #182, but fairly easy to redo #201 after #182 is merged.

**Comment by benanne** [comment]
Sure!

**Comment by benanne** [comment]
I'm redoing this instead of rebasing because there are so few changes that it's easier.

**Comment by f0k** [comment]
You could just have done that in the same PR, though, by force-pushing to the `mergelayer` branch.

**Comment by benanne** [comment]
I guess. Doesn't really matter :)

**Comment by f0k** [comment]
Something like:
```bash
git checkout master
git branch -D mergelayer
git checkout -b mergelayer
# do your changes and commit
git push --force origin mergelayer
```
You can still do that and reopen the PR.

**Pull request closed without merging**
