### PR TITLE
improve test coverage

### PR DESCRIPTION
**Pull request by benanne**
This is going to be a collection of tests to improve test coverage across the library. So far I've only done `base.py`, which should now be 100% covered when we get rid of the deprecated stuff. Other than that I'll be focusing mostly on the convolution implementations for now. If anyone wants to help we can try to divide the work a little. It would be nice to get the coverage up in the 90%+ range before we release the library :)

For clarity's sake, I'm of course aware that good coverage does not necessarily mean the tests are good - but it's an important first step!

### CODE REVIEW

**Comment by dnouri** [comment]
This trick might be useful if you want to ignore coverage of deprecated functions or the like: http://nedbatchelder.com/code/coverage/excluding.html

**Comment by benanne** [comment]
Good to know! Probably not worth it yet though, all of that code is going away in a matter of weeks anyway :) But I'll keep it in mind for later.

**Comment by f0k** [comment]
> Probably not worth it yet though

I think it wouldn't hurt to add `#pragma: no cover` comments to the deprecated function definitions as part of the effort to increase coverage. The comments will go away along with the deprecated functions, and it will make it easier to hunt down the important uncovered cases. So don't hesitate to drop those comments where you see fit.

**Comment by benanne** [comment]
True, I guess I can do it as I go through the coverage reports.

**Comment by ebenolson** [comment]
Should probably ask, is the ultimate intention 100% coverage across the board? 
Testing for every little thing can get a bit silly, but it is a nice tangible goal.

The files currently needing coverage (most to least) are:
- [ ] lasagne/updates
- [ ] lasagne/layers/cuda_convnet
- [ ] lasagne/layers/pool
- [ ] lasagne/layers/helper
- [ ] lasagne/utils
- [ ] lasagne/layers/shape
- [ ] lasagne/layers/dnn
- [ ] lasagne/layers/conv
- [ ] lasagne/layers/corrmm
- [ ] ~~lasagne/objectives~~
- [ ] lasagne/layers/merge
- [ ] ~~lasagne/regularization~~
- [ ] lasagne/layers/normalization
- [ ] lasagne/layers/input

I'm planning to continue working my way up the list and grab some more low hanging fruit.

I'm ignoring objectives and regularization for now, since they will probably change more before first release.

**Comment by benanne** [comment]
I don't think we need to worry about getting it to 100% right now, there are probably other matters that are more deserving of our attention. But it would be nice to have it somewhere in the 90%+ range before we release.

From that list I would focus on updates, helper and pool next if I were you :) I plan to sort out the convolution code myself since I know that part of the codebase very well. But if I'm not going fast enough to your liking feel free to take some of that off my hands as well ;)

**Comment by ebenolson** [comment]
Sounds good. I think the conv stuff is going to be a bit of a pain, since most of what's uncovered are the various special restrictions that the generic tests avoid.

**Comment by benanne** [comment]
Yep... probably :p I have a feeling there might be a few bugs lurking there as well though.

**Comment by benanne** [comment]
Maybe the todo list should be moved to #112, so we don't lose track of it once this PR is merged.

**Comment by ebenolson** [comment]
Makes sense, too bad it's not possible to edit other peoples comments.

**Comment by benanne** [comment]
I'll merge this tomorrow and do the convolution tests in one or more separate PRs.

**Pull request merged**
