### PR TITLE
Mock theano.config so GPU-dependent modules show up on readhtedocs.org

### PR DESCRIPTION
**Pull request by benanne**
I have no way to test this, I think... unless readthedocs.org can build docs off a branch as a test, I'll look into that (but I doubt it). Suggestions to maximize the chance of this working are very welcome :)

### CODE REVIEW

**Comment by dnouri** [comment]
I'm afraid that in the case of dnn.py, you'll also need to mock `theano.sandbox.cuda.dnn.dnn_available` to return True.

I just tried this little script which worked on a non-GPU box:

```python
from unittest.mock import Mock

import theano
import theano.sandbox.cuda

theano.config = Mock(device="gpu")
theano.sandbox.cuda.dnn = Mock(dnn_available=lambda: True)

import lasagne.layers.dnn  # works
```

**Comment by benanne** [comment]
Thanks for checking! So this should do it then I guess :)

**Comment by benanne** [comment]
I will merge this and see what happens. Worst case it won't work, but I don't think I can break anything else with this.

**Comment by benanne** [comment]
Looks like it wasn't enough:

```
/var/build/user_builds/lasagne/checkouts/latest/docs/modules/layers.rst:111: WARNING: autodoc: failed to import module u'lasagne.layers.corrmm'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lasagne/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lasagne/envs/latest/local/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/corrmm.py", line 16, in <module>
    from theano.sandbox.cuda.blas import GpuCorrMM
ImportError: cannot import name GpuCorrMM
/var/build/user_builds/lasagne/checkouts/latest/docs/modules/layers.rst:118: WARNING: autodoc: failed to import module u'lasagne.layers.cuda_convnet'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/lasagne/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/lasagne/envs/latest/local/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/cuda_convnet.py", line 14, in <module>
    from pylearn2.sandbox.cuda_convnet.filter_acts import FilterActs
ImportError: No module named pylearn2.sandbox.cuda_convnet.filter_acts
```

**Comment by dnouri** [comment]
This turns out to be a FAQ: http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

I think something like `sys.modules['pylearn2.sandbox.cuda_convnet.filter_acts'] = Mock()` should work.

**Comment by benanne** [comment]
I guess that's worth a try as well, then maybe we can leave the imports themselves unchanged.

**Comment by dnouri** [comment]
I just tried this without a GPU and it looks like Sphinx was able to import the cuda_convnet module fine with this change.

**Comment by benanne** [comment]
Yep, I'm updating the new PR to do this instead.

**Pull request merged**
