### PR TITLE
Gpuarray

### PR DESCRIPTION
**Pull request by borisfom**
This should address https://github.com/Lasagne/Lasagne/issues/698

### CODE REVIEW

**Comment by f0k** [comment]
Thanks for your contribution! Unfortunately, this is (a) not entirely correct (see the failing tests) and (b) removes compatibility with the old backend. As detailed in https://github.com/Lasagne/Lasagne/issues/698#issuecomment-290702908, I'd prefer a PR that makes Lasagne compatible with both backends, and only drop compatibility to the old backend when Lasagne requires Theano 0.10 (which won't have the old backend). Furthermore, as detailed in https://github.com/Lasagne/Lasagne/issues/698#issuecomment-290538224, Lasagne already works with the new backend anyway, only the implementation-specific convolutional layers don't (but they're usually not needed).

I think @Sentient07 may also work on a PR for dual-backend compatibility. @Sentient07, Is that true? I'm just assuming based on your questions in #698.

Otherwise, are you interested in extending your PR towards both backends? This will require more than a simple search & replace; we'll need to figure out how to test for CUDA support in a backend-agnostic way (without importing sandbox.cuda in case the new backend is used), do conditional imports of the cuDNN and gemm Ops (in layers/dnn and layers/corrmm), and possibly adapt the faked CUDA support for Sphinx accordingly.

**Comment by Sentient07** [comment]
@f0k yes, i started working on it yesterday, addressing the places that Pascal suggested. I still have a little bit of cleanup remaining before I open a PR. 

>  and possibly adapt the faked CUDA support for Sphinx accordingly.

I don't understand this. could you please elaborate? Is it about updating the documentation ?

**Comment by f0k** [comment]
> I don't understand this. could you please elaborate? Is it about updating the documentation ?

No, it's about rendering the documentation. The online documentation is built at readthedocs, which doesn't have a GPU. In order to render the documentation for `lasagne.layers.dnn`, Sphinx still has to be able to import `lasagne.layers.dnn` at readthedocs, despite the missing GPU support. To do that, we had to fake GPU support in the Sphinx configuration for Lasagne: https://github.com/Lasagne/Lasagne/blob/master/docs/conf.py#L319-L340
If we change the GPU support check in `lasagne.layers.dnn` (https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/dnn.py#L13-L21), which we have to do in order to support both backends, then we may also have to update the faked GPU support in the Sphinx configuration (i.e., find another hack that allows to import `lasagne.layers.dnn` without a GPU).

**Comment by Sentient07** [comment]
That made things much clear! Thank you

**Comment by f0k** [comment]
#836 provides a solution that support both backends, so I'll close this. The suggested documentation/docstring changes will be useful later. Thank you!

**Pull request closed without merging**
