### PR TITLE
TransposedConv3DLayer

### PR DESCRIPTION
**Pull request by FabianIsensee**
Second attempt ;-)

### CODE REVIEW

**Comment by f0k** [comment]
Pushed mine again. I wonder why the first commit is not attributed to you any more. It's authored by "Fabian Ibensee" in the log, using your heidelberg email address.

**Comment by FabianIsensee** [comment]
Hm yeah I would very much like to retain the authorship of that commit. Do you know how we could fix this? I am not much of a git ninja

**Comment by f0k** [comment]
I've changed it such that both the author and committer are your name and heidelberg email address. Is that a different one than you registered on github?

**Comment by FabianIsensee** [comment]
Oh I did the new pull request form a laptop at home where I did not have github set properly. The email address is correct though (gmail and heidelberg are both fine). I now added the heidelberg address to github as well

**Comment by FabianIsensee** [comment]
Hm now you don't show up anymore... Or am I missing something?

**Comment by f0k** [comment]
> I now added the heidelberg address to github as well

You always had the heidelberg address in the commits, but probably github knew it was you because you pushed them.

> Hm now you don't show up anymore...

That was on purpose. I just rearranged things and fixed a small error (you removed one of the checks in docs/conf.py and duplicated another). I think it's good to merge now. Will merge in the evening or so if there are no other comments.

**Comment by FabianIsensee** [comment]
OK great! Thank you!

**Pull request merged**
