### PR TITLE
Documentation: Sphinx format to numpydoc format

### PR DESCRIPTION
**Pull request by MartinThoma**
See issue #203

### CODE REVIEW

**Comment by benanne** [comment]
Looks great! For some reason our current template makes it look pretty crappy :( it renders all the argument descriptions as blockquotes or something, and the font sizes don't make any sense at all. I wonder if this needs to be fixed by changing the theme, or by adapting our markup.

**Comment by benanne** [comment]
It looks like this problem is inherent to the combination of `sphinx_bootstrap_theme` and the `numpydoc` format, which is pretty disappointing. I had a look at this: https://github.com/biocore/scikit-bio/

They also use this combination, and it looks like they have a custom CSS file to fix the font sizes. We should probably do the same (in a separate PR).

I really don't understand why this is so broken by default, it's quite frustrating to not be able to make the docs look good without resorting to custom code.

**Comment by MartinThoma** [comment]
That's bad :-(

I really would like it if we had the same theme/structure as scipy has.
Especially the overview pages (e.g.
http://docs.scipy.org/doc/scipy/reference/linalg.html) and a separate page
per class (e.g.
http://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.diagsvd.html#scipy.linalg.diagsvd
).

This looks very clean, can be indexed by Google / linked by people and is
nice for just looking whats there.

A little drawback of their theme is the missing search bar.


2015-04-12 16:02 GMT+02:00 Sander Dieleman <notifications@github.com>:

**Comment by benanne** [comment]
I don't think our classes are usually complicated enough to warrant a separate page :) But I do like the overviews.

**Comment by benanne** [comment]
If you don't mind, I would like to wait to merge this until we are done with #182. I have a strong suspicion that rebasing #182 would be more painful than rebasing this PR :)

**Comment by MartinThoma** [comment]
Sure, no problem. I think doing this completely again would take me about 20 minutes.

**Comment by benanne** [comment]
It took longer than expected, but #182 has been merged so it's time to get our docs in order! Are you okay with rebasing this? If you don't have time for this right now let us know, maybe someone else can do it.

**Comment by f0k** [comment]
Also if you don't know how to go about it, there are two options.
Rebasing:
```bash
git checkout master
git fetch upstream
git merge --ff-only upstream/master
git checkout docs
git rebase master
# solve conflicts by editing the files it reports as conflicting, "git add" them and "git rebase --continue"
git push --force origin docs
```
Redoing:
```bash
git checkout master
git branch -D docs  # delete current version of the branch
git checkout -b docs  # create new version from master
# redo your changes and commit them
git push --force origin docs
```

**Comment by benanne** [comment]
@MartinThoma if you are not able to do this in the next few days, are you okay with me rebasing this and creating a new PR from it? Your commits will still be there so you will still be credited nevertheless :) I'd like to finish #228 and I need to extend the docs you wrote.

**Comment by MartinThoma** [comment]
@benanne Sure, go ahead (I'm sorry, I don't have enough time the next days. I have to figure out how to do semantic segmentation with Caffe for a course at university.)

**Comment by benanne** [comment]
No worries, good luck with the assignment :)

**Comment by benanne** [comment]
The rebased version is at #250, I will close this PR.

**Pull request closed without merging**
