### PR TITLE
Update mnist.py

### PR DESCRIPTION
**Pull request by vikaschawlavc**

### CODE REVIEW

**Comment by benanne** [comment]
Could you clarify why you think this change is necessary? It looks like `gzip` is already imported where it is needed, but perhaps I'm missing something :)

**Comment by vikaschawlavc** [comment]
It was giving error on my system without that line. :) Maybe i was doing something wrong..!!

**Comment by benanne** [comment]
That's weird, as far as I can see the only function that uses the module also imports it in the function body. So this shouldn't happen. Could you provide the error message + backtrace? Thanks!

**Comment by f0k** [comment]
Tried the unmodified mnist.py with python 2.7 and 3.4, there were no problems with a missing `gzip` module or anything. Closing this issue. Please feel free to reopen if you can reproduce the error and post a full traceback!

**Pull request closed without merging**
