### PR TITLE
Replace masked code in all recurrent layers by T.switch command

### LINKED ISSUE #550: Use theano.tensor.switch in LSTM Layer in masked step
I'm curious why theano.tensor.switch isn't used in the following place: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/recurrent.py#L1077

not_mask = 1 - mask_n
cell = cell*mask_n + cell_previous*not_mask
hid = hid*mask_n + hid_previous*not_mask

we can rewrite this code as following:

cell = T.switch(mask_n, cell, cell_previous)
hid = T.switch(mask_n, hid, hid_previous)

How I see it runs with the same speed but anyway why you don't use 'switch'?

### PR DESCRIPTION
**Pull request by avostryakov**
Replace masked code in all recurrent layers by T.switch command

Closes #550.

### CODE REVIEW

**Comment by skaae** [comment]
It looks good to me. Thanks.

**Comment by benanne** [comment]
Looks good to me as well. I'll let you do the honours :)

**Comment by f0k** [comment]
Looks good, it's cleaner and shouldn't hurt (the previous implementation allows to do some tricks with non-binary masks, but probably nobody did that).
@craffel: Was there a specific reason for not using `T.switch()`? Did you observe that multiplication to be faster (contrary to the cursory test in #550)?

**Comment by skaae** [comment]
I think i did the masking implementation. I don't think there was a particular reason for not using `T.switch`

**Comment by craffel** [comment]
I think there was some reference implementation somewhere from the Theano folks who used the multiplication trick.  Great that switch is faster, thanks for this.

**Comment by f0k** [comment]
All right, merging then! Thanks again!

**Pull request merged**
