### PR TITLE
Bayes by Backprop

### PR DESCRIPTION
**Pull request by Ferrine**
From Issue #699

Hi, I have some issues with tests and generating HTML docs
Tests(I use PyCharm):
```
Process finished with exit code 2
Empty test suite.
```
HTML:
My files are unseen

### CODE REVIEW

**Comment by Ferrine** [comment]
Here I propose a lightweight implementation of Bayes By Backprop[1] algorithm that is aimed on fitting posterior distribution.  That allows to make some decisions about out belief in prediction. It is possible to compute some metrics like mode, median, mean, variance and so on. For instance we can construct posterior confidence interval for prediction, compute the chance of mistake in some binary tasks. In most real world tasks it is crucial to now risks, i.e. medicine. 

I think that my implementation will cope with most Layers that exist in this repo and custom ones. They only need to add param with `add_param` method
## Usage example:
```python
# common imports
import lasagne
import theano.tensor as T
from lasagne.layers.dense import DenseLayer
from lasagne.layers.input import InputLayer
from lasagne.init import Normal
from lasagne.nonlinearities import tanh, sigmoid
#    Constants for more clear code
N_HIDDEN = 5
N_BATCHES = 100
```
### Before
```python
l_in = l_in = InputLayer((10,100))
l1_hidden = DenseLayer(l_in, num_units=N_HIDDEN, W=Normal(1), b=Normal(1),
                       nonlinearity=tanh)
l1_out = DenseLayer(l1_hidden, num_units=1, W=Normal(1), b=Normal(1),
                       nonlinearity=sigmoid)
# got it, now create objective
true_output = T.ivector('true_output')
net_output = lasagne.layers.get_output(l_output).ravel()
all_params = lasagne.layers.get_all_params(l_output)
objective = lasagne.objectives.binary_crossentropy(net_output, true_output)
objective = objective.sum()
# train it as you wish
```
### What I propose
```python
from lasagne.layers.bayes import (bbpwrap,
                                  NormalApproximation,
                                  NormalApproximationScMix,
                                  Accumulator)
#    1. Choose your favorite Layer
#    2. Wrap your favorite Layer
@bbpwrap(NormalApproximation(pstd=1))
class BayesDenseLayer(DenseLayer):
    pass
#    Gracias! It's bayesian!
#    And another
@bbpwrap(NormalApproximationScMix(pm1=.0, pstd1=.5, pm2=.0, pstd2=1e-3, pi=.5))
class BayesDenseLayer2(DenseLayer):
    pass
#    3. Create the thing that will do some dirty work for us,
#        it will collect all variational cost
acc = Accumulator()

l_in = InputLayer((10,100))

#    4. Pass `acc` as first argument
l1_hidden = BayesDenseLayer(acc, l_in, num_units=N_HIDDEN,
                             W=Normal(1), b=Normal(1),
                             nonlinearity=tanh)

#    Also possible to specify both mu and rho
myW = {'mu':Normal(1.5), 'rho':Normal(.1)}
l_output = BayesDenseLayer2(acc, l1_hidden, num_units=1,
                           W=myW, b=Normal(1),
                           nonlinearity=sigmoid)
net_output = lasagne.layers.get_output(l_output).ravel()
true_output = T.ivector('true_output')

#    5. That thing has collected the variational cost,
#       all we need is to get it and add to our objective
#       Do not forget to scale variational cost!
#       .. Note
#           Binary crossentropy is exactly the same as binomial
#           likelihood
objective = lasagne.objectives.binary_crossentropy(net_output,
                                                    true_output)
objective = objective.sum()
objective += (acc.get_cost() / N_BATCHES)

#    6. Choose adam optimizer for training
all_params = lasagne.layers.get_all_params(l_output)
updates = lasagne.updates.adam(objective, all_params)
```
Calculating them can be very useful. You can answer some real world questions like "what's tha chance that prediction is wrong?". Or you can calculate mean "confidence" for dataset and decide if it is overconfident or not.
### Results
bbp
### Training process
train_cost
test_err

References:
    [1] Charles Blundell, Julien Cornebise,
           Koray Kavukcuoglu, Daan Wierstra (2015):
           Weight Uncertainty in Neural Networks [arXiv:1505.05424](http://arxiv.org/abs/1505.05424)

**Comment by Ferrine** [comment]
I read [post](http://blog.shakirm.com/2015/10/machine-learning-trick-of-the-day-4-reparameterisation-tricks/) on Reddit and now thinking about generalizing reparametrization trick so that it will be easy to add user defined approximation family in future and play with it like with a constructor.

**Comment by benanne** [comment]
> BTW parmesan seems to be better place to contribute

I am inclined to agree, this might be a bit too specialized to add to the main library -- especially considering that it requires the introduction of a new API, which we always try to be extremely careful about :)

**Comment by Ferrine** [comment]
Ye, definitely! The only reason I opened first PR not in parmesan was that parmesan did not support python3. That was not so hard to fix and I hope my PR will be merged there.

BTW does `create_param` accepts a callable that returns `theano.Variable`?

**Comment by benanne** [comment]
Yes, support for this was recently added in #695 :)

**Pull request closed without merging**
