### PR TITLE
Fix comments (input shape description) in LSTM and GRU classes

### PR DESCRIPTION
**Pull request by avostryakov**

### CODE REVIEW

**Comment by skaae** [comment]
I think the original comment is correct?

**Comment by avostryakov** [comment]
A shape of input variable should be (n_time_steps, n_batch, n_features). It is input to LSTM layer. And it is multiplied on W_in_stacked which has a shape (n_features, 4*num_units):

(n_time_steps, n_batch, n_features) x (n_features, 4*num_units) = (n_time_steps, n_batch, 4*num_units)

I can't multiply (n_time_steps, n_batch, 4*num_units) x (n_features, 4*num_units)

**Comment by skaae** [comment]
True. I missed the input above. I'm fine with merging.

**Comment by f0k** [comment]
> I can't multiply (n_time_steps, n_batch, 4num_units) x (n_features, 4num_units)

That's not what the comment wants to say. It's meant to say what `input` looks like *after* that multiplication. Granted, it's not formulated very clearly!

Closing a) because it's not the correct fix, and b) because it conflicts with #629. Comment fixes should better be made there to avoid rebasing, please feel free to comment on the diff of that PR!

**Pull request closed without merging**
