### PR TITLE
Clarifying comment for iterate_minibatches in mnist example

### PR DESCRIPTION
**Pull request by mehdidc**
Fix iterate_minibatches function in case nb of inputs < batchsize, if nb inputs < batchsize it does not iterate through available inputs, I know it does not make sense to have nb inputs < batchsize but it should do the correct thing if it is.

### CODE REVIEW

**Comment by f0k** [comment]
The promise of the `iterate_minibatches` function is to always return batches of `batchsize` items, and no half-filled batches. Your proposal would drop the last (half-filled) batch for datasets that have more than `batchsize` items, but return it for all smaller datasets. That's inconsistent. The current function always drops the last half-filled batch, even if it would have been the only one.
If anything, we could change the code to return half-filled batches for validation/testing, but for the MNIST example we've tailored the batch size to the size of the validation and test set to avoid this case altogether.
I'm leaning towards leaving such modifications to users basing their code on the MNIST example.

**Comment by benanne** [comment]
> I'm leaning towards leaving such modifications to users basing their code on the MNIST example.

Agreed, we could maybe add some comments to clarify what's happening though, so people can decide for themselves whether they need to modify this behaviour or not.

**Comment by mehdidc** [comment]
Thanks for the feedback, @f0k and @benanne, Ok I see, actually my proposal should have been  'for start_idx in range(0, len(inputs), batchsize)', anyway, indeed it would be nice indeed  to add some comments explaining what is happening.

**Comment by f0k** [comment]
Perfect, even squashed into a single commit already. Merging, thank you!

**Pull request merged**
