### PR TITLE
Some docstring fixes

### PR DESCRIPTION
**Pull request by f0k**
Since @kli-nlpr is doing a docstring review (thanks!), I'm committing some things I found myself last week. Merging can wait a bit, maybe I'll notice more.

### CODE REVIEW

**Comment by kli-nlpr** [comment]
In fact, I am reading the source code of Lasagne and learn a lot from this great project.
Because docstring is very important for a new guy to correctly use Lasagne,
I hope to make some small contributions that I can to this wonderful project.
:smile:

**Comment by benanne** [comment]
Thanks a lot for that, this is work that often gets swept under the rug because it's not the most fun thing to do, but it is very important. We really appreciate it!

**Comment by f0k** [comment]
Open to be merged. I can always start a new PR for additional doc fixes.

**Comment by benanne** [comment]
LGTM, merging!

**Pull request merged**
