### PR TITLE
spelling correction

### PR DESCRIPTION
**Pull request by jcatw**
Corrects the spelling of multiclass_hinge_loss (was mutliclass_hinge_loss)

### CODE REVIEW

**Comment by f0k** [comment]
Woops, thanks. This needs to be fixed in `test_objectives.py` as well, can you amend your commit? (Edit the file, do `git add lasagne/tests/test_objectives.py`, then `git commit --amend -m 'Fix spelling of multiclass_hinge_loss()'`, then `git push --force`.)

**Comment by jcatw** [comment]
Sure thing, incoming shortly.

**Comment by jcatw** [comment]
Ok, done.

**Comment by f0k** [comment]
Great, thanks for spotting it that quickly!

**Pull request merged**
